-- Mapping: m_EDM_DW_SSP_FINC_LOB_DIM
-- Generated from Informatica Knowledge Graph
-- Parameters: none
--
-- Source: SSP_FINC_LOB_DIM_V1
-- Target: SSP_FINC_LOB_DIM
--
-- TODO: Confirm FINC_LOB_CD is unique in both source and target. BigQuery MERGE
--       raises an error when multiple source rows match the same target row.

MERGE `@{PROJECT_ID}.@{DATASET}.SSP_FINC_LOB_DIM` AS T
USING (
  WITH cte_SQ_SSP_FINC_LOB_DIM_V1 AS (
    SELECT
      CAST(SSP_FINC_LOB_DIM_Key AS INT64) AS SSP_FINC_LOB_DIM_Key,
      TIMESTAMP(StartDate, 'America/New_York') AS StartDate,
      TIMESTAMP(EndDate, 'America/New_York') AS EndDate,
      CAST(IsCurrent AS STRING) AS IsCurrent,
      CAST(SourceSystemKey AS STRING) AS SourceSystemKey,
      CAST(SourceSystemID AS INT64) AS SourceSystemID,
      CAST(FINC_LOB_CD AS STRING) AS FINC_LOB_CD,
      CAST(FINC_LOB_ARBR_CD AS STRING) AS FINC_LOB_ARBR_CD,
      CAST(FINC_LOB_NM AS STRING) AS FINC_LOB_NM,
      CAST(FINC_LOB_BUS_NM AS STRING) AS FINC_LOB_BUS_NM,
      CAST(FINC_LOB_BUS_NM_UAT AS STRING) AS FINC_LOB_BUS_NM_UAT,
      CAST(FINC_LOB_HRCHY_ID AS STRING) AS FINC_LOB_HRCHY_ID,
      TIMESTAMP(ACTV_DT, 'America/New_York') AS ACTV_DT,
      TIMESTAMP(INACTV_DT, 'America/New_York') AS INACTV_DT,
      CAST(IS_ACTV_IND AS STRING) AS IS_ACTV_IND,
      CAST(DIM_SRC_CD AS STRING) AS DIM_SRC_CD,
      TIMESTAMP(DIM_LAST_MDFD_DT, 'America/New_York') AS DIM_LAST_MDFD_DT,
      CAST(FINC_LOB_HRCHY_LVL1 AS STRING) AS FINC_LOB_HRCHY_LVL1,
      CAST(FINC_LOB_HRCHY_LVL2 AS STRING) AS FINC_LOB_HRCHY_LVL2,
      CAST(FINC_LOB_HRCHY_LVL3 AS STRING) AS FINC_LOB_HRCHY_LVL3
    FROM `@{PROJECT_ID}.@{DATASET}.SSP_FINC_LOB_DIM_V1`
  ),

  cte_LKP_SSP_FINC_LOB_DIM AS (
    SELECT
      S.*,
      LKP.FINC_LOB_CD_SK AS LKP_FINC_LOB_CD_SK
    FROM cte_SQ_SSP_FINC_LOB_DIM_V1 AS S
    LEFT JOIN `@{PROJECT_ID}.@{DATASET}.SSP_FINC_LOB_DIM` AS LKP
      ON LKP.FINC_LOB_CD = S.FINC_LOB_CD
  ),

  cte_RTR_INSERT_UPDATE AS (
    SELECT
      CASE
        WHEN LKP_FINC_LOB_CD_SK IS NULL THEN 'INSERT'
        ELSE 'UPDATE'
      END AS ROUTE_ACTION,
      CAST(
        CASE
          WHEN LKP_FINC_LOB_CD_SK IS NULL
            THEN SSP_FINC_LOB_DIM_Key
          ELSE LKP_FINC_LOB_CD_SK
        END AS NUMERIC
      ) AS FINC_LOB_CD_SK,
      FINC_LOB_CD,
      FINC_LOB_ARBR_CD,
      FINC_LOB_NM,
      FINC_LOB_BUS_NM,
      FINC_LOB_BUS_NM_UAT,
      FINC_LOB_HRCHY_ID,
      ACTV_DT,
      INACTV_DT,
      IS_ACTV_IND,
      DIM_SRC_CD,
      DIM_LAST_MDFD_DT,
      FINC_LOB_HRCHY_LVL1,
      FINC_LOB_HRCHY_LVL2,
      FINC_LOB_HRCHY_LVL3
    FROM cte_LKP_SSP_FINC_LOB_DIM
  )

  SELECT *
  FROM cte_RTR_INSERT_UPDATE
) AS S
ON T.FINC_LOB_CD = S.FINC_LOB_CD

WHEN MATCHED AND S.ROUTE_ACTION = 'UPDATE' THEN
  UPDATE SET
    FINC_LOB_CD_SK = S.FINC_LOB_CD_SK,
    FINC_LOB_CD = S.FINC_LOB_CD,
    FINC_LOB_ARBR_CD = S.FINC_LOB_ARBR_CD,
    FINC_LOB_NM = S.FINC_LOB_NM,
    FINC_LOB_BUS_NM = S.FINC_LOB_BUS_NM,
    FINC_LOB_BUS_NM_UAT = S.FINC_LOB_BUS_NM_UAT,
    FINC_LOB_HRCHY_ID = S.FINC_LOB_HRCHY_ID,
    ACTV_DT = S.ACTV_DT,
    INACTV_DT = S.INACTV_DT,
    IS_ACTV_IND = S.IS_ACTV_IND,
    DIM_SRC_CD = S.DIM_SRC_CD,
    DIM_LAST_MDFD_DT = S.DIM_LAST_MDFD_DT,
    FINC_LOB_HRCHY_LVL1 = S.FINC_LOB_HRCHY_LVL1,
    FINC_LOB_HRCHY_LVL2 = S.FINC_LOB_HRCHY_LVL2,
    FINC_LOB_HRCHY_LVL3 = S.FINC_LOB_HRCHY_LVL3

WHEN NOT MATCHED AND S.ROUTE_ACTION = 'INSERT' THEN
  INSERT (
    FINC_LOB_CD_SK,
    FINC_LOB_CD,
    FINC_LOB_ARBR_CD,
    FINC_LOB_NM,
    FINC_LOB_BUS_NM,
    FINC_LOB_BUS_NM_UAT,
    FINC_LOB_HRCHY_ID,
    ACTV_DT,
    INACTV_DT,
    IS_ACTV_IND,
    DIM_SRC_CD,
    DIM_LAST_MDFD_DT,
    FINC_LOB_HRCHY_LVL1,
    FINC_LOB_HRCHY_LVL2,
    FINC_LOB_HRCHY_LVL3
  )
  VALUES (
    S.FINC_LOB_CD_SK,
    S.FINC_LOB_CD,
    S.FINC_LOB_ARBR_CD,
    S.FINC_LOB_NM,
    S.FINC_LOB_BUS_NM,
    S.FINC_LOB_BUS_NM_UAT,
    S.FINC_LOB_HRCHY_ID,
    S.ACTV_DT,
    S.INACTV_DT,
    S.IS_ACTV_IND,
    S.DIM_SRC_CD,
    S.DIM_LAST_MDFD_DT,
    S.FINC_LOB_HRCHY_LVL1,
    S.FINC_LOB_HRCHY_LVL2,
    S.FINC_LOB_HRCHY_LVL3
  );
